# Generated by Django 4.2.1 on 2023-05-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_education_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='level',
            field=models.CharField(blank=True, choices=[('b', 'کارشناسی'), ('m', 'کارشناسی ارشد'), ('phd', 'دکترا')], max_length=50, null=True, verbose_name='مقطع'),
        ),
    ]
