# Generated by Django 4.2.1 on 2023-05-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='start_update',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='شروع '),
        ),
        migrations.AlterField(
            model_name='education',
            name='start',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='شروع '),
        ),
    ]
