# Generated by Django 4.2.1 on 2023-05-12 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_person_alter_education_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='talebi',
            new_name='family',
        ),
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 12, 15, 38, 38, 837667, tzinfo=datetime.timezone.utc), null=True, verbose_name='پایان '),
        ),
        migrations.AlterField(
            model_name='education',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 15, 38, 38, 837667, tzinfo=datetime.timezone.utc), null=True, verbose_name='شروع '),
        ),
    ]
