# Generated by Django 4.2.1 on 2023-05-12 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_talebi_person_family_alter_education_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'فرد '},
        ),
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 12, 15, 39, 28, 843587, tzinfo=datetime.timezone.utc), null=True, verbose_name='پایان '),
        ),
        migrations.AlterField(
            model_name='education',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 15, 39, 28, 843587, tzinfo=datetime.timezone.utc), null=True, verbose_name='شروع '),
        ),
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
    ]
