# Generated by Django 4.2.1 on 2023-05-12 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_person_options_alter_education_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='educations',
            field=models.ManyToManyField(to='blog.education'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='پایان '),
        ),
        migrations.AlterField(
            model_name='education',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='شروع '),
        ),
    ]
