# Generated by Django 4.2.1 on 2023-05-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_skills_person_picture_alter_person_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'مهارت ها '},
        ),
        migrations.AlterModelTable(
            name='skills',
            table='skills',
        ),
    ]
