# Generated by Django 4.2.1 on 2023-05-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_skills_options_alter_skills_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='tools',
            field=models.CharField(blank=True, max_length=200, verbose_name='ابزار ها '),
        ),
    ]
