# Generated by Django 4.2.1 on 2023-05-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='experiences',
            field=models.ManyToManyField(blank=True, null=True, to='blog.experience'),
        ),
    ]
