# Generated by Django 4.2.1 on 2023-05-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_person_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Linkedin',
            field=models.CharField(max_length=200, verbose_name='آدرس لینک دین '),
        ),
        migrations.AlterField(
            model_name='person',
            name='git_hub_slug',
            field=models.CharField(max_length=200, verbose_name='آدرس گیت هاب    '),
        ),
    ]
