# Generated by Django 4.2.1 on 2023-05-13 14:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_person_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='applications',
            field=ckeditor.fields.RichTextField(verbose_name='کاربرد ها '),
        ),
    ]
