# Generated by Django 4.2.1 on 2023-05-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_skills_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Expert', 'Expert'), ('professional', 'professional'), ('Professor', 'Professor')], max_length=30, verbose_name='سطح مهارت'),
        ),
    ]
