# Generated by Django 4.2.1 on 2023-05-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_education_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, upload_to='Image_person', verbose_name='عکس علاقه مندی')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام علاقه مندی')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='interests',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس'),
        ),
    ]
