# Generated by Django 4.2.1 on 2023-05-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_interests_alter_person_interests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interests',
            options={'verbose_name_plural': 'علاقه مندی ها '},
        ),
        migrations.AlterModelTable(
            name='interests',
            table='interests',
        ),
    ]
